server:
  port:8083
spring:
  application:
    name: checkout
  datasource:
    url: ${db.uri.auth.checkout}
    username: ${db.username.auth}
    password: ${db.password.auth}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    username: {rabbitmq.username}
    password: {rabbitmq.password}
    host: {rabbitmq.host}
    port: 5672

  cloud:
    stream:
      function:
        definition: checkoutEventListener
        bindings:
          checkoutEventListener-in-0:
            destination: app.v1.event.checkout
            group: checkout

  api:
    security:
      token: {payment.token}
      group: Grupo10
      members:
        - Rafael Amaral
        - Andr√© S Ferreira
        - Giulliana Munhoz
        - Tiago Santana
        - Eduardo Vilhena